config/routes.rb
Rails.application.routes.draw do
  get 'rents/index'
  devise_for :users
  resources :rooms
  resources :rents, only: [:create, :index] do
    collection do
      post :confirm
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "homes#top"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :check_in_date, presence: true
  validates :check_out_date, presence: true
  validates :total_people, presence: true

  def save_rent(rent, rent_params)
    rent.check_in_date = rent_params[:check_in_date]
    rent.check_out_date = rent_params[:check_out_date]
    rent.total_people = rent_params[:total_people]
    rent.total_day = rent_params[:total_day]
    rent.total_amount = rent_params[:total_amount]
    rent.user_id = rent_params[:user_id]
    rent.room_id = rent_params[:room_id]
    save
  end

  def sum_of_days
    (check_out_date.to_date - check_in_date.to_date).to_i if check_in_date.present? && check_out_date.present?
  end

  def sum_of_amount
    (room.amount * total_people * sum_of_days).to_i if check_in_date.present? && check_out_date.present?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :rents
  validates :name, presence: true
  validates :amount, presence: true

  def rents_new
    rents.new
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rents
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def index
    @rents = Rent.all
  end

  def confirm
    @room = Room.find(params[:rent][:room_id])
    @user = User.find(params[:rent][:user_id])
    @check_in_date = params[:rent][:check_in_date]
    @check_out_date = params[:rent][:check_out_date]
    @total_people = params[:rent][:total_people]
    @total_day = params[:rent][:total_day]
    @total_amount = params[:rent][:total_amount]
    @rent = Rent.find_by(params[:id])
    @room = Room.find_by(params[:id])
  end

  def create
    @rent = Rent.new(rent_params)
    @rent.total_day = @rent.sum_of_days
    @rent.total_amount = @rent.sum_of_amount

    if @rent.save
      redirect_to rents_url, notice: '予約が確定しました。'
    else
      @room = @rent.room
      @user = @rent.user
      @check_in_date = @rent.check_in_date
      @check_out_date = @rent.check_out_date
      @total_people = @rent.total_people
      render :comfirm, status: :unprocessable_entity
    end
  end

  private
    def rent_params
      params.require(:rent).permit(:check_in_date, :check_out_date, :total_people, :total_day, :total_amount, :room_id, :user_id).
             merge(user_id: current_user.id, room_id: params[:room_id])
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(params.require(:room).permit(:name, :amount))
    if @room.save
      flash[:notice] = "部屋を新規登録しました"
      redirect_to :rooms
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @room = Room.find(params[:id])
    @rents = @room.rents
    @rent = @rents.new
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(params.require(:room).permit(:name, :amount))
      flash[:notice] = "ルームIDが「#{@room.id}」の情報を更新しました"
      redirect_to :rooms
    else
      render "edit"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>H</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>ホテルの宿泊アプリ</h1>
    <h1>バリデーションの実装</h1>
    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <ul>
      <li><%= link_to "サインアップ", :new_user_registration %></li>
      <li><%= link_to "ログイン", :new_user_session %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "ログアウトしますか？" } %></li>
      <li><%= link_to "部屋一覧", :rooms %></li>
      <li><%= link_to "借りた部屋一覧", :rents_index %></li>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/rents/confirm.html.erb
<h1>app/views/rents/confirm.html.erb</h1>
<h1>予約確認</h1>
<h1>エラーメッセージの実装</h1>
<%= render "layouts/errors", obj: @rent %>

<p>部屋名: <%= @room.name %></p>
<p>チェックイン: <%= @check_in_date %></p>
<p>チェックアウト: <%= @check_out_date %></p>
<p>合計人数: <%= @total_people %></p>
<%= render "layouts/errors", obj: f.object %>

<%= form_with url: rents_path, method: :post, local: true, data: { turbo: false } do |f| %>
  <%= hidden_field_tag :room_id, @room.id %>
  <%= hidden_field_tag :user_id, current_user.id %>
  <%= f.hidden_field :check_in_date, value: @check_in_date, name: 'rent[check_in_date]' %>
  <%= f.hidden_field :check_out_date, value: @check_out_date, name: 'rent[check_out_date]' %>
  <%= f.hidden_field :total_people, value: @total_people, name: 'rent[total_people]' %>
  <%= f.submit "予約を確定する" %>
<% end %>
<P><%= link_to "キャンセル", :back %></P>

app/views/rents/create.html.erb
<h1>Rents#create</h1>
<p>Find me in app/views/rents/create.html.erb</p>

app/views/rents/index.html.erb
<h1>rents/index.html.erb</h1>
<h1>予約一覧</h1>
<% @rents.each do |rent| %>
  <table class="show-table">
    <tr>
      <th>部屋名</th>
      <td><%= rent.room.name %></td>
    </tr>
    <tr>
      <th>チェックイン</th>
      <td><%= rent.check_in_date %></td>
    </tr>
    <tr>
      <th>チェックアウト</th>
      <td><%= rent.check_out_date %></td>
    </tr>
    <tr>
      <th>支払い合計金額</th>
      <td><%= rent.sum_of_amount %>円</td>
    </tr>
    <tr>
      <th>予約した日にち</th>
      <td><%= rent.created_at %></td>
    </tr>
    <p>--------------------------------------------------</p>
  </table>
<% end %>

app/views/rooms/index.html.erb
<h1>Rooms#index</h1>
<p>Find me in app/views/rooms/index.html.erb</p>
<h1>部屋情報一覧</h1>
<table>
  <thead>
    <tr>
      <th>ROOM ID</th>
      <th>名前</th>
      <th>金額</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.id %></td>
        <td><%= room.name %></td>
        <td><%= room.amount %></td>
        <td><%= link_to "詳細", room %></td>
        <td><%= link_to "編集", [:edit, room] %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p><%= link_to "部屋新規登録", :new_room %></p>
<p><%= link_to "ホーム", :root %></p>

app/views/rooms/new.html.erb
<h1>Rooms#new</h1>
<p>Find me in app/views/rooms/new.html.erb</p>
<%= render "layouts/errors", obj: @room %>
<h1>部屋新規作成</h1>
<%= form_with model: @room do |f| %>
<table>
  <tr>
    <th><%= f.label :name ,"名前" %></th>
    <td><%= f.text_field :name %></td>
  </tr>

  <tr>
    <th><%= f.label :amount, "金額" %></th>
    <td><%= f.number_field :amount %></td>
  </tr>
</table>
<div>
  <ul>
    <li><%= f.submit "部屋を登録する"%></li>
    <li><%= link_to "部屋情報一覧に戻る", :rooms %></li>
  </ul>
</div>
<% end %>

app/views/rooms/show.html.erb
<h1>Rooms#show</h1>
<p>Find me in app/views/rooms/show.html.erb</p>
<h1>部屋詳細</h1>
<table>
  <tr>
    <th>名前</th>
    <td><%= @room.name %></td>
  </tr>
  <tr>
    <th>金額</th>
    <td><%= @room.amount %></td>
  </tr>
</table>

<% if user_signed_in? %>
  <h1>予約フォーム</h1>
  <h1>必須項目</h1>
  <%= form_with url: confirm_rents_path, method: :post, local: true, data: { turbo: false } do |f| %>
  <ul>
    <%= f.hidden_field :room_id, value: @room.id, name: 'rent[room_id]' %>
    <%= f.hidden_field :user_id, value: current_user.id, name: 'rent[user_id]' %>
    <li>チェックイン<%= f.date_field :check_in_date, value: @rent.check_in_date, name: 'rent[check_in_date]' %></li>
    <li>チェックアウト<%= f.date_field :check_out_date, value: @rent.check_out_date, name: 'rent[check_out_date]' %></li>
    <li>合計人数<%= f.number_field :total_people, value: 1, name: 'rent[total_people]' %></li>
    <li><%= f.submit "確認画面へ" %></li>
  </ul>
  <% end %>
<% end %>
<div>
  <p><%= link_to "部屋情報一覧に戻る", :rooms %></p>
</div>